services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER:    "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB:      "${DB_NAME}"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mori"]
      interval: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
  go-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mori-go-backend
    depends_on:
     postgres:
       condition: service_healthy
    working_dir: /app
    ports:
      - "8081:8081"  
    env_file:
      - ./backend/.env 

    restart: unless-stopped

  llm-server:
    build:
      context: ./backend/logic_llm
      dockerfile: Dockerfile
    container_name: mori-llm-server
    working_dir: /app
    volumes:
      - ./backend/logic_llm:/app
    command: ["poetry", "run", "uvicorn", "server:app", "--host", "0.0.0.0", "--port", "3000","--reload"]
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: mori-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "serve"]
    ports:
      - "8080:8080"
    restart: unless-stopped
volumes:
  pgdata: