name: mori-workflow

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read


jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: sudo apt-get install gh -y
    - name: Run tests (example)
      run: |
        echo "Running tests..."
        # Ajoutez ici vos scripts de test
    - name: Auto Assign Reviewers
      uses: kentaro-m/auto-assign-action@v2.0.0
      with:
        configuration-path: '.github/auto-assign.yml'

    - name: Ensure PR requires review
      if: github.event.pull_request.draft == false
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Ensure PR has an approval."
        approvals=$(gh pr view ${{ github.event.pull_request.number }} --json reviews --jq '.reviews | map(select(.state == "APPROVED")) | length')
        if [ "$approvals" -lt 1 ]; then
          echo "This PR does not have any approvals yet."
          exit 1
        fi